export const FETCH_COMPETITIONS_START = 'FETCH_COMPETITIONS_START';
export const FETCH_COMPETITIONS_SUCCESS = 'FETCH_COMPETITIONS_SUCCESS';
export const FETCH_COMPETITIONS_FAILURE = 'FETCH_COMPETITIONS_FAILURE';

export const FETCH_COMPETITION_START = 'FETCH_COMPETITION_START';
export const FETCH_COMPETITION_SUCCESS = 'FETCH_COMPETITION_SUCCESS';
export const FETCH_COMPETITION_FAILURE = 'FETCH_COMPETITION_FAILURE';

export const FETCH_SEASON_START = 'FETCH_SEASON_START';
export const FETCH_SEASON_SUCCESS = 'FETCH_SEASON_SUCCESS';
export const FETCH_SEASON_FAILURE = 'FETCH_SEASON_FAILURE';

export const FETCH_SEASON_MATCHES_START = 'FETCH_SEASON_MATCHES_START';
export const FETCH_SEASON_MATCHES_SUCCESS = 'FETCH_SEASON_MATCHES_SUCCESS';
export const FETCH_SEASON_MATCHES_FAILURE = 'FETCH_SEASON_MATCHES_FAILURE';

export const CHANGE_YEAR_IN_COMPETITIONS = 'CHANGE_YEAR_IN_COMPETITIONS';
export const CHANGE_SEASON_IN_COMPETITION = 'CHANGE_SEASON_IN_COMPETITION';

export const FETCH_TEAM_START = 'FETCH_TEAM_START';
export const FETCH_TEAM_SUCCESS = 'FETCH_TEAM_SUCCESS';
export const FETCH_TEAM_FAILURE = 'FETCH_TEAM_FAILURE';

export const FETCH_TEAM_MATCHES_START = 'FETCH_TEAM_MATCHES_START';
export const FETCH_TEAM_MATCHES_SUCCESS = 'FETCH_TEAM_MATCHES_SUCCESS';
export const FETCH_TEAM_MATCHES_FAILURE = 'FETCH_TEAM_MATCHES_FAILURE';